### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by VitorLuizC** [VitorLuizC/vue-custom-properties-parallax#1]
Transform it in a module and publish on NPM.

#### Tasks

- [x] Create a `package.json`;
- [x] Add @nobrefelipe as creator and me as maintainer;
- [x] Exports directive and install function;
  - Exporting it's directive allow users to install locally on components or mixins;
  - Exporting a install function allow globally install this directive.
- [x] Choose a name or use `vue-css-parallax-variable`.

**Comment by VitorLuizC** [comment]
`vue-parallax-vars` is the chosen one.

**Comment by VitorLuizC** [comment]
PR about it https://github.com/nobrefelipe/vue-css-variable-parallax/pull/1

**Comment by VitorLuizC** [comment]
Closed since this was merged on upstream repository.
